import ctypes as C

from collections.abc import Callable
from typing import Any, Literal

def ensure_byte_string(value : str | bytes) -> bytes: ...

def ensure_unicode_string(value : str | bytes) -> str: ...

def property_value_to_bytes(value : Any) -> bytes: ...

def string_to_bool(value : str) -> bool: ...

def udev_list_iterate(libudev : C.CDLL, entry : Any) -> tuple[bytes, bytes]: ...

def get_device_type(filename : str) -> Literal["char", "block"]: ...

def eintr_retry_call(func : Callable[..., Any], *args : Any, **kwargs : Any) -> Any: ...

def udev_version() -> int: ...
